// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBER0AxSdXe_1a9sFcUxkD6bKDJ5pf3mlU',
    appId: '1:741691049863:web:36e57099eaa2173e10f522',
    messagingSenderId: '741691049863',
    projectId: 'html-c8675',
    authDomain: 'html-c8675.firebaseapp.com',
    storageBucket: 'html-c8675.firebasestorage.app',
    measurementId: 'G-0F0XSQJ5XC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKbX3uRnADW0Uei3wzhwX7IqY8-_RmSO0',
    appId: '1:741691049863:android:930a6208907467d210f522',
    messagingSenderId: '741691049863',
    projectId: 'html-c8675',
    storageBucket: 'html-c8675.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz1go4QEw1lW235OLPhV8suNf8jVOT49A',
    appId: '1:741691049863:ios:ad8bdaf101172de310f522',
    messagingSenderId: '741691049863',
    projectId: 'html-c8675',
    storageBucket: 'html-c8675.firebasestorage.app',
    iosBundleId: 'com.example.htmlLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz1go4QEw1lW235OLPhV8suNf8jVOT49A',
    appId: '1:741691049863:ios:ad8bdaf101172de310f522',
    messagingSenderId: '741691049863',
    projectId: 'html-c8675',
    storageBucket: 'html-c8675.firebasestorage.app',
    iosBundleId: 'com.example.htmlLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBER0AxSdXe_1a9sFcUxkD6bKDJ5pf3mlU',
    appId: '1:741691049863:web:d5dab07f3017733010f522',
    messagingSenderId: '741691049863',
    projectId: 'html-c8675',
    authDomain: 'html-c8675.firebaseapp.com',
    storageBucket: 'html-c8675.firebasestorage.app',
    measurementId: 'G-FWHTL96807',
  );
}
